### ISSUE TITLE
Why was Sitegeist "retired"?

### ISSUE THREAD

**Issue by miguelpaz** [sunlightlabs/sitegeist#17]
Can you share the reasons why this amazing project was retired? Did it take too much maintenance work or any other issues? I am interested because I am researching for a project that taps in to many API`s and I am checking what are the risks

**Comment by jcarbaugh** [comment]
We are a nonprofit and were unable to find the funding needed to keep the project alive. The monthly costs were minimal and required almost no staff intervention, but some data was years out of data and the native mobile apps were aging and breaking. The fixes for these issues required a relatively small budget, but big enough of a budget that we were unable to find the funding for it.

**Comment by miguelpaz** [comment]
Thanks for your answer @jcarbaugh.

**Comment by jcarbaugh** [comment]
Sure thing. Hope that helps!
